server:
  port: "8080"
  readTimeoutSeconds: 5
  writeTimeoutSeconds: 10

infrastructure:
  retry:
    maxAttempts: 10
    delaySeconds: 2

api:
  gatewayUrl: ""

templates:
  path: "internal/web/template"