server:
  port: "8080"
  readTimeoutSeconds: 5
  writeTimeoutSeconds: 10

infrastructure:
  retry:
    maxAttempts: 20
    delaySeconds: 5

api:
  gatewayUrl: ""

templates:
  path: "internal/web/template"